### ISSUE TITLE
Change the connection strings

### ISSUE THREAD

**Issue by anhlee24** [digipolisantwerp/dataaccess_aspnetcore#13]
How i can change the connection strings?, i used MSSQL. 

Thank you.

**Comment by pradeepind** [comment]
Please change the settings in DataAccess.SampleApp/_config/dataaccess.json and change the options.UseNpgsql to options.UseSqlServer in DataAccess.SampleApp/Startup.cs. Make sure you switch out the postgres nuget package with Sql server

**Comment by anhlee24** [comment]
Thank you.
