### ISSUE TITLE
Order by Function usage

### ISSUE THREAD

**Issue by anhlee24** [digipolisantwerp/dataaccess_aspnetcore#15]
Hi,

` List<UrlRecord> urlRecords = null;

            using (var uow = _uowProvider.CreateUnitOfWork(false))
            {
                Filter<UrlRecord>
                filter = new Filter<UrlRecord>(null);

                filter.AddExpression(e => e.EntityId == entityId 
                                        && e.EntityName == entityName
                                        && e.LanguageId == languageId);

                var repository = uow.GetRepository<UrlRecord>();
                **var orderBy = new OrderBy<UrlRecord>(string.IsNullOrEmpty(paging.Sort) ? "Reservation.DateOfReservation" : paging.Sort, paging.Descending);**
                urlRecords = (repository.Query(filter.Expression, orderBy, null)).ToList();
            }`

i am not sure about orderby arguments, can you give me an example for this?

Thank you.

**Comment by StevenVandenBroeck** [comment]
To order by e.g. EntityName you have two options : 

with an expression : 

`var orderBy = new OrderBy<UrlRecord>(query => query.OrderBy(ur => ur.EntityName));`

or with a string column name :

`var orderBy = new OrderBy<UrlRecord>("EntityName", true)`   // true/false for asc/desc

**Comment by anhlee24** [comment]
Thank you! 
You have a great project!

**Comment by StevenVandenBroeck** [comment]
Thanks :-)
