### ISSUE TITLE
Join 2 or more tables

### ISSUE THREAD

**Issue by anhlee24** [digipolisantwerp/dataaccess_aspnetcore#19]
How can i join 2 or more 2 tables (these table haven't relationship)?

Thank you. :)

**Comment by StevenVandenBroeck** [comment]
If you don't have [navigation](https://docs.efproject.net/en/latest/modeling/relationships.html#fully-defined-relationships) properties, you will have to join yourself :

`...from x in Entity1 join y in Entity2 on x.JoinProperty equals y.JoinProperty`

or with lambda expressions :

`context.MyEntity.Join(...)`

You can find more info here : https://code.msdn.microsoft.com/101-LINQ-Samples-3fb9811b

**Comment by anhlee24** [comment]
Thank you, i have did it as you suggest.

Can you add an method for this?

**Comment by StevenVandenBroeck** [comment]
That is not a standard scenario. Normally you would use navigation properties.
