### ISSUE TITLE
Include inner join

### ISSUE THREAD

**Issue by coskuncinar** [digipolisantwerp/dataaccess_aspnetcore#20]
Hi,
I wanna take inner join in query when  im using  include?
How to make this?

**Comment by StevenVandenBroeck** [comment]
When you define navigation properties in your entities en use the Include method, you will get an inner join. You can find more information about navigation properties and Include in the Entity Framework documentation : http://ef.readthedocs.io/en/latest/querying/related-data.html.
Using our framework, you can pass an IncludeList to the repositories : https://github.com/digipolisantwerp/dataaccess_aspnetcore#includes

**Comment by coskuncinar** [comment]
i found what i m looking feature in your framework.
in fact i'm looking "Many-to-many: Without join entity"
But  in this version of efcore it does not support this feature.
I hope , they will improve it...
