### ISSUE TITLE
GetProperty problem in core 1.0.1

### ISSUE THREAD

**Issue by mohsenpourian** [digipolisantwerp/dataaccess_aspnetcore#25]
hi
i get error in 

(OrderBy.cs) : after updating sample app core packages

`PropertyInfo propertyInfo = entityType.GetProperty(propertyName, BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance);`

Error:
**'Type' does not contain a definition for 'GetProperty' and no extension method 'GetProperty' accepting a...**

**Comment by StevenVandenBroeck** [comment]
Did you upgrade all the needed packages ?

**Comment by mohsenpourian** [comment]
solved by update, thanks.
