### ISSUE TITLE
Primary key data type other than integer

### ISSUE THREAD

**Issue by pkapare** [digipolisantwerp/dataaccess_aspnetcore#28]
Hi,
I liked this library very much. Thanks for good work. I have question though. Currently EntityBase class in library is defined as follows.
public class EntityBase
    {
        [Key]
        public int Id { get; set; }
    }

What if I need to use different Key i.e. GUID as key or instead of "Id" name use different Key e.g. "UserId". 
Is there any way I can override data type and name of Key property here?  If not name then at least data type?
Regards
Pankaj

**Comment by StevenVandenBroeck** [comment]
That's not possible right now with this library. What you can do is fork the repository and change the EntityBase class for yourself.
