### ISSUE TITLE
Register two database context

### ISSUE THREAD

**Issue by kenneth-y** [digipolisantwerp/dataaccess_aspnetcore#31]
Hi,

Do you have a sample on using two database context in a single app? In my app i did like below.

`services.AddDbContext<DbContext1>();`
`services.AddDataAccess<DbContext1>();`

`services.AddDbContext<DbContext2>();`
`services.AddDataAccess<DbContext2>();`

DbContext1 and DbContext2 are configured to connect to a different SQL DB but i noticed the queries seems to always go to DbContext1.

Appreciate your inputs and advice to help me put in the right track.
Thanks.

**Comment by StevenVandenBroeck** [comment]
Hi, thanks for your request. 
The current version of our library can only work with 1 DbContext and we have no immediate plans to change this, but you are free to try it yourself.
