### ISSUE TITLE
How to work fine with  IdentityDbContext

### ISSUE THREAD

**Issue by FreezeSoul** [digipolisantwerp/dataaccess_aspnetcore#32]
how to compatible asp.net identity:

my code is here:
public class MyContext : IdentityDbContext<User, Role, long>
public partial class User : IdentityUser<long>

can EntityBase and EntityContextBase change to interface?

**Comment by StevenVandenBroeck** [comment]
Hi,
our framework is not compatible with the ASP.NET Identity package. They use their own structure to query/update the database (RoleStore, UserStore, ...).
You can use our framework for your own data access code and entities.

**Comment by FreezeSoul** [comment]
thanks, i'll try it

**Comment by mortenbirkelund** [comment]
Are there any workaround for this, except creating another context? Currently I use only one context for the whole application, I would like to continue doing so. But i would also like to use your awesome project ;)

**Comment by anhlee24** [comment]
Are there a solution for it?
this project very good and i like it.

**Comment by StevenVandenBroeck** [comment]
Sorry @mortenbirkelund and @anhlee24 but there is no out-of-the-box solution for this. The ASP.NET Core  Identity package uses its own structure to access the database. What you can do is create 1 DbContext with our framework for your business data access and another DbContext for the Identity stuff.

**Comment by anhlee24** [comment]
@StevenVandenBroeck  no problem. thanks for your reply so much.

Can you add some methods for working with Store procedure or View. It will very great!

**Comment by StevenVandenBroeck** [comment]
@anhlee24, you can to this easily yourself by writing a custom repository, inheriting from RepositoryBase.
