### ISSUE TITLE
Reason of IUnitOfWork and UnitOfWork

### ISSUE THREAD

**Issue by mohsen-bandamir** [digipolisantwerp/dataaccess_aspnetcore#34]
Hi;
What's the reason for creating IUnitOfWork and UnitOfWork in Uow Layer? 
Is it for customization? For example add custome function in UnitOfWork?
Why methods like SaveChanges and SaveChangesAsync signature exist in both IUnitOfWork and IUnitOfWorkBase?

thanks in advance

**Comment by StevenVandenBroeck** [comment]
Hi,

the UnitOfWork is an abstraction layer that hides the EF context and other data access code from the rest of the (business) code. This way you have better separation and code that is easier to test (and a mockable data layer).
