### ISSUE TITLE
Update/Delete/Insert in a bulk

### ISSUE THREAD

**Issue by anhlee24** [digipolisantwerp/dataaccess_aspnetcore#37]
Hi,

This is an great job, its clear and easy to custom.
I can insert/update/delete for single item now. Can i do it with multi items?

Some things like:
Item.Save(); // for single item
ItemList.Save(); // for multi items

Thanks,
Thanh.

**Comment by StevenVandenBroeck** [comment]
With 1 IUnitOfWork, you can add, update and delete different items through the repositorie. Then, when you call the IUnitOfWork.SaveChanges() method at the end, all changes will be persisted to the database in 1 transaction. EF Core will try to do this in batches.

**Comment by anhlee24** [comment]
Thank you.
