### ISSUE TITLE
ViewModel or Dto, How to

### ISSUE THREAD

**Issue by m2017atTR** [digipolisantwerp/dataaccess_aspnetcore#38]
I think i need help about Tnetity Mapping,
I dont want to return all fields to client as described in model

Is there any solution for mapping ?

**Comment by davidsheardown** [comment]
I use automapper which works really well with .NET Core.  I am in a rush at the moment, so will try to post an example soon.

But if you search for automapper and .NET Core, that might get you started

**Comment by StevenVandenBroeck** [comment]
If you use our generic repositories you can use AutoMapper or an equivalent library to easily copy only the needed fields to a new DTO object, like @davidsheardown  said. It's always better to not expose your entities to the client but to copy the data to a DTO object first. Downside to using our generic repositories for this is that you retrieve more fields from the database than the client needs.
If you really only want to retrieve the needed fields from the database, you will have to return a projection with a custom LINQ to Entities query where you only request the needed fields. You will have to make a custom repository for that.

**Comment by m2017atTR** [comment]
I started using AutoMapper . 
Thanks for help.
