### ISSUE TITLE
Include with filter

### ISSUE THREAD

**Issue by m2017atTR** [digipolisantwerp/dataaccess_aspnetcore#39]
Is that possible to add filter to included entities.. I want only subcategories that active is true

          Func<IQueryable<Category>, IQueryable<Category>> func = 
                 query => {
                    return query.Include(b => b.SubCategories)
                                .ThenInclude(a => a.SubCategories);
                 };
          await repository.QueryAsync(
                  t => 
                        t.ParentId == parentId && t.active == true && t.skipmenu == false, 
                        null,
                        func
          );

**Comment by StevenVandenBroeck** [comment]
@m2017atTR ,

you can find more info on how to filter with EF Core in their docs, here : https://docs.microsoft.com/en-us/ef/core/querying/related-data. Look for the chapter 'Querying related entities'.
