### ISSUE TITLE
error CS1061 DbContextOptionsBuilder

### ISSUE THREAD

**Issue by Kris-I** [digipolisantwerp/dataaccess_aspnetcore#41]
Hello,

When I use SQL Server, the compilation ok but at runtime I get this error
_error CS1061 DbContextOptionsBuilder does not contain a definition for 'UseSQLServer' and no extension method 'UseSQLServer'_

public void ConfigureServices(IServiceCollection services)
{
	services.AddDbContext<SampleAppContext>(options => options.UseSqlServer(".......")); //(A)
	services.AddDataAccess<SampleAppContext>();
	services.AddMvc();
}

The error occur on line (A) .

The reference about EntitiyFramework are 1.1.2 and the using are 
_using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore;_

I really don't understand :(

Thanks,

**Comment by StevenVandenBroeck** [comment]
Hi @Kris-I,

do you have a reference to Microsoft.EntityFrameworkCore.SqlServer in your project ?

**Comment by Kris-I** [comment]
After a long long investigation the cause is .... "CodeRush" from DevExpress. When it's disabled(or removed) no more problem.

**Comment by StevenVandenBroeck** [comment]
Strange...but I'm glad you found it.
