### ISSUE TITLE
Can not register DbContext in startup.cs

### ISSUE THREAD

**Issue by anhlee24** [digipolisantwerp/dataaccess_aspnetcore#8]
I have this DbContext:
`public class WorldContext : EntityContextBase<IdentityDbContext<WorldUser>>
 {
}`
then in startup.cs, i add the following in ConfigureServices:
`services.AddDataAccess<WorldContext>();`

Then i met the error:
`The type 'TheWorld.Models.WorldContext' cannot be used as type parameter 'TEntityContext' in the generic type or method 'ServiceCollectionExtentions.AddDataAccess<TEntityContext>(IServiceCollection)'. There is no implicit reference conversion from 'TheWorld.Models.WorldContext' to 'Digipolis.DataAccess.Context.EntityContextBase<TheWorld.Models.WorldContext>'.	
`

**Comment by StevenVandenBroeck** [comment]
Try to use your context as generic parameter to the EntityContextBase class,  like this :  
`public class WorldContext : EntityContextBase<WorldContext> { }`

https://github.com/digipolisantwerp/dataaccess_aspnetcore#entitycontext

**Comment by anhlee24** [comment]
Thank you, i found it 5m ago. 

Its easy to use than i thought.

I have modify EntityContextBase to use with IdentityContext, is it right way?

`public class EntityContextBase<TContext> : IdentityDbContext<UserIdentityClass>, IEntityContext where TContext : DbContext
    {
        public EntityContextBase(DbContextOptions<TContext> options) : base(options)
        {
        }
    }`

**Comment by StevenVandenBroeck** [comment]
Yes, if you want to use IdentityDbContext as base.
